version: '3.7'
services:
    deathrun:
        image: "ceifa/gmod-server:root"
        ports: 
            - "27017:27017"
            - "27017:27017/udp"
        volumes:
            - ./servers/_build/deathrun/addons:/server/garrysmod/addons
            - ./servers/_build/deathrun/cfg:/server/garrysmod/cfg
            - ./servers/_build/deathrun/data:/server/garrysmod/data
            - ./servers/_build/deathrun/gamemodes:/server/garrysmod/gamemodes
            - ./servers/_stateful/deathrun/sv.db:/server/garrysmod/sv.db
            - ./servers/_stateful/deathrun/debug.log:/server/debug.log
            - ./servers/_stateful/cache:/server/garrysmod/cache
            - ./servers/_stateful/steam_cache:/server/steam_cache/content
        environment:
            - PRODUCTION=0
            - PORT=27017
            - NAME=[BR] Lory | Deathrun ~ 128 tickrate ~ Divirta-se!
            - ARGS=+host_workshop_collection 382793424 -tickrate 100
            - MAP=deathrun_atomic_warfare
            - GAMEMODE=deathrun
            - MAXPLAYERS=24
        restart: always
        stdin_open: true
        tty: true
        networks:
            - lory

    murder:
        image: "ceifa/gmod-server:root"
        ports: 
            - "27018:27018"
            - "27018:27018/udp"
        volumes:
            - ./servers/_build/murder/addons:/server/garrysmod/addons
            - ./servers/_build/murder/cfg:/server/garrysmod/cfg
            - ./servers/_build/murder/data:/server/garrysmod/data
            - ./servers/_build/murder/gamemodes:/server/garrysmod/gamemodes
            - ./servers/_stateful/murder/sv.db:/server/garrysmod/sv.db
            - ./servers/_stateful/murder/debug.log:/server/debug.log
            - ./servers/_stateful/cache:/server/garrysmod/cache
            - ./servers/_stateful/steam_cache:/server/steam_cache/content
        environment:
            - PRODUCTION=0
            - PORT=27018
            - NAME=[BR] Lory | Murder ~ [[ VIP GRATIS LIMITADO! ]] ~ Divirta-se!
            - ARGS=+host_workshop_collection 1581506103 -tickrate 100
            - MAP=gm_wwhouse
            - MAP=gm_construct
            - GAMEMODE=murder
            - MAXPLAYERS=24
        restart: always
        tty: true
        networks:
            - lory

networks:
    lory: