name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Build deathrun
      run: |
        mkdir garrysmod
        cp -R ./servers/_shared/* garrysmod/
        cp -R ./servers/deathrun/* garrysmod/

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Deathrun distributable
        path: garrysmod

   
  deploy:
    runs-on: ubuntu-18.04
    needs: [build]

    steps:
    - uses: actions/checkout@v2
    
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: Deathrun distributable
        path: garrysmod

    - name: Upload deathrun addons
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.DEATHRUN_FTP_SERVER }}
        ftp-username: ${{ secrets.DEATHRUN_FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: garrysmod/addons
        git-ftp-args: --insecure --remote-root ./garrysmod/addons
